# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Ingredient.destroy_all

condiments = [
  "aji amarillo",
  "apple sauce",
  "bacon jam",
  "banana pepper rings",
  "bbq sauce",
  "beer mustard",
  "black olives",
  "bonito flakes",
  "bread &amp; butter pickles",
  "brown mustard",
  "buffalo sauce",
  "candied jalapenos",
  "canned mushroom",
  "capers",
  "chamoy",
  "chermoula",
  "chili crisp",
  "chili jam",
  "chili paste",
  "chili sauce",
  "chili-garlic sauce",
  "chipotle in adobo",
  "chutney",
  "corn relish",
  "cranberry sauce",
  "crispy onions",
  "dark soy sauce",
  "dijon mustard",
  "dill relish",
  "doubanjiang",
  "duck sauce",
  "duqqa",
  "eel sauce",
  "english mustard",
  "fish sauce",
  "german mustard",
  "ginger chili paste",
  "ginger-garlic paste",
  "gochujang",
  "green olives",
  "harissa",
  "honey mustard",
  "horseradish mustard",
  "hot sauce",
  "hp sauce",
  "jalapeno jelly",
  "kalamata olives",
  "kecap manis",
  "ketchup",
  "kimchi",
  "lime pickle",
  "mango chutney",
  "mint jelly",
  "mustard",
  "okra pickles",
  "oyster sauce",
  "peri peri",
  "picante sauce",
  "piccalilli",
  "pickapeppa sauce",
  "pickle",
  "pickled beets",
  "pickled ginger",
  "pickled green beans",
  "pickled jalapenos",
  "pickled onions",
  "pickled red onion",
  "pickled vegetables",
  "pickling juice",
  "pimiento-stuffed green olives",
  "ponzu",
  "preserved lemon",
  "red pepper jelly",
  "red pepper relish",
  "sauerkraut",
  "shrimp paste",
  "shrimp sauce",
  "soy sauce",
  "spicy brown mustard",
  "sriracha",
  "sun dried tomato",
  "sweet and sour sauce",
  "sweet pickle relish",
  "taggiasca olives",
  "tamari",
  "tartar sauce",
  "tau pan cheong",
  "teriyaki sauce",
  "tomato in oil",
  "tomato jelly",
  "tomato relish",
  "tonkatsu sauce",
  "truffle juice",
  "vinegar peppers",
  "white bbq sauce",
  "wholegrain mustard",
  "worcestershire",
  "yakisoba sauce",
  "yuzu juice",
  "zha cai"]

condiments.each do |c|
  Ingredient.create(name: c, category: "Condiments")
end